name: CI/CD - Build and Deploy Next.js App

on:
  push:
    branches:
      - master # Change this to your main branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Change this to your desired Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to cPanel
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22 # Change this if your cPanel uses a different SSH port
          script: |
            cd public_html
            rm -rf *  # Remove old files
            cp -r ../build/. ./  # Copy the built Next.js app
